#!/usr/bin/env bash

set -euo pipefail

version="v0.3.00"
app_name="airplay2-receiver"
ota_file="${app_name}-esp32s3-${version}-ota.bin"
install_file="${app_name}-esp32s3-${version}-install.bin"
checksum_file="SHA256SUMS-${version}.txt"

rm -f sdkconfig sdkconfig.old
rm -rf build

idf.py \
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.esp32s3" \
  build

cp "build/${app_name}.bin" "${ota_file}"

(
  cd build
  # flash_args is generated by ESP-IDF and contains the correct offsets.
  # shellcheck disable=SC2046
  esptool.py --chip esp32s3 merge_bin --format raw \
    -o "../${install_file}" \
    $(cat flash_args)
)

python3 .github/scripts/validate-esp32s3-bin.py "${install_file}"

sha256sum "${install_file}" "${ota_file}" > "${checksum_file}"

echo "Build files created successfully:"
ls -lh "${install_file}" "${ota_file}" "${checksum_file}"
